config/routes.rb
BillboardIntegration::Application.routes.draw do
  resources :transmitters

  resources :receivers

  resources :sightings

  root :to => 'sightings#index'
  match 'billboard_1/status' => 'status#billboard_1'
  match 'billboard_2/status' => 'status#billboard_2'

end

app/models/transmitter.rb
class Transmitter < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/transmitters_controller.rb
class TransmittersController < ApplicationController
  # GET /transmitters
  # GET /transmitters.json
  def index
    @transmitters = Transmitter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transmitters }
    end
  end

  # GET /transmitters/1
  # GET /transmitters/1.json
  def show
    @transmitter = Transmitter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transmitter }
    end
  end

  # GET /transmitters/new
  # GET /transmitters/new.json
  def new
    @transmitter = Transmitter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transmitter }
    end
  end

  # GET /transmitters/1/edit
  def edit
    @transmitter = Transmitter.find(params[:id])
  end

  # POST /transmitters
  # POST /transmitters.json
  def create
    @transmitter = Transmitter.new(params[:transmitter])

    respond_to do |format|
      if @transmitter.save
        format.html { redirect_to @transmitter, notice: 'Transmitter was successfully created.' }
        format.json { render json: @transmitter, status: :created, location: @transmitter }
      else
        format.html { render action: "new" }
        format.json { render json: @transmitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transmitters/1
  # PUT /transmitters/1.json
  def update
    @transmitter = Transmitter.find(params[:id])

    respond_to do |format|
      if @transmitter.update_attributes(params[:transmitter])
        format.html { redirect_to @transmitter, notice: 'Transmitter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transmitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transmitters/1
  # DELETE /transmitters/1.json
  def destroy
    @transmitter = Transmitter.find(params[:id])
    @transmitter.destroy

    respond_to do |format|
      format.html { redirect_to transmitters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/transmitters_helper.rb
module TransmittersHelper
end

app/views/transmitters/_form.html.erb
<%= form_for(@transmitter) do |f| %>
  <% if @transmitter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transmitter.errors.count, "error") %> prohibited this transmitter from being saved:</h2>

      <ul>
      <% @transmitter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transmitters/edit.html.erb
<h1>Editing transmitter</h1>

<%= render 'form' %>

<%= link_to 'Show', @transmitter %> |
<%= link_to 'Back', transmitters_path %>

app/views/transmitters/index.html.erb
<h1>Listing transmitters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transmitters.each do |transmitter| %>
  <tr>
    <td><%= transmitter.name %></td>
    <td><%= transmitter.description %></td>
    <td><%= link_to 'Show', transmitter %></td>
    <td><%= link_to 'Edit', edit_transmitter_path(transmitter) %></td>
    <td><%= link_to 'Destroy', transmitter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transmitter', new_transmitter_path %>

app/views/transmitters/new.html.erb
<h1>New transmitter</h1>

<%= render 'form' %>

<%= link_to 'Back', transmitters_path %>

app/views/transmitters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @transmitter.name %>
</p>

<p>
  <b>Description:</b>
  <%= @transmitter.description %>
</p>


<%= link_to 'Edit', edit_transmitter_path(@transmitter) %> |
<%= link_to 'Back', transmitters_path %>