config/routes.rb
BillboardIntegration::Application.routes.draw do
  resources :transmitters

  resources :receivers

  resources :sightings

  root :to => 'sightings#index'
  match 'billboard_1/status' => 'status#billboard_1'
  match 'billboard_2/status' => 'status#billboard_2'

end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  attr_accessible :receiver_name, :transmitter_name, :rssi
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  # GET /sightings
  # GET /sightings.json
  def index
    @sightings = Sighting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sightings }
    end
  end

  # GET /sightings/1
  # GET /sightings/1.json
  def show
    @sighting = Sighting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sighting }
    end
  end

  # GET /sightings/new
  # GET /sightings/new.json
  def new
    @sighting = Sighting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sighting }
    end
  end

  # GET /sightings/1/edit
  def edit
    @sighting = Sighting.find(params[:id])
  end

  # POST /sightings 
  # POST /sightings.json

  def create
    if params[:transmitter_name] && params[:receiver_name]
      @sighting = Sighting.new(:transmitter_name => params[:transmitter_name], :receiver_name => params[:receiver_name])
    end

    if @sighting && @sighting.save
      redirect_to @sighting, notice: 'Sighting event was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /sightings/1
  # PUT /sightings/1.json
  def update
    @sighting = Sighting.find(params[:id])

    respond_to do |format|
      if @sighting.update_attributes(params[:sighting])
        format.html { redirect_to @sighting, notice: 'Sighting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sightings/1
  # DELETE /sightings/1.json
  def destroy
    @sighting = Sighting.find(params[:id])
    @sighting.destroy

    respond_to do |format|
      format.html { redirect_to sightings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/views/sightings/_form.html.erb
<%= form_for(@sighting) do |f| %>
  <% if @sighting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sighting.errors.count, "error") %> prohibited this sighting from being saved:</h2>

      <ul>
      <% @sighting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sightings/edit.html.erb
<h1>Editing sighting</h1>

<%= render 'form' %>

<%= link_to 'Show', @sighting %> |
<%= link_to 'Back', sightings_path %>

app/views/sightings/index.html.erb
<h1>Listing sightings</h1>

<table>
  <tr>
    <th>RX Name</th>
    <th>Tx Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sightings.each do |sighting| %>
  <tr>
    <td><%= sighting.receiver_name %></td>
    <td><%= sighting.transmitter_name %></td>
    <td><%= link_to 'Show', sighting %></td>
    <td><%= link_to 'Edit', edit_sighting_path(sighting) %></td>
    <td><%= link_to 'Destroy', sighting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sighting', new_sighting_path %>

app/views/sightings/new.html.erb
<h1>New sighting</h1>

<%= render 'form' %>

<%= link_to 'Back', sightings_path %>

app/views/sightings/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_sighting_path(@sighting) %> |
<%= link_to 'Back', sightings_path %>